spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic?useSSL=false&serverTimezone=UTC
    username: root
    password: tarrafal92
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/clinicdb

server:
  port: 8080

jwt:
  secret: our-very-long-secret-key-minimum-32-characters-for-security
  expiration: 3600000